services:
  - type: web
    name: pretreino-mock-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: WEBHOOK_SECRET
        sync: false
